require(... .. ".plugins.alpha")
require(... .. ".plugins.lsp")
require(... .. ".plugins.lspsaga")
require(... .. ".plugins.telescope")
require(... .. ".plugins.treesitter")
require(... .. ".plugins.undotree")
require(... .. ".plugins.neotree")
require(... .. ".plugins.which_key")
require(... .. ".plugins.barbar")
require(... .. ".plugins.possession")
require(... .. ".plugins.gitsigns")
require(... .. ".plugins.marks")
require(... .. ".plugins.nvim_spectre")
require(... .. ".plugins.trouble")
require(... .. ".plugins.todo_comments")
require(... .. ".plugins.nvim_ts_autotag")
require(... .. ".plugins.scope")


-- INFO: ui
require(... .. ".ui.lualine")
require(... .. ".ui.colorscheme")
